source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SACountingLabel_Example', :exclusive => true do
  pod "SACountingLabel", :path => "../"
end

target 'SACountingLabel_Tests', :exclusive => true do
  pod "SACountingLabel", :path => "../"
end
